version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(TF)"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "dependencies"
      - "patch"
