- block:
  - name: Update the image packages
    ansible.builtin.apt:
      update_cache: true
      upgrade: full

  when: skip_image_upgrade|default(false)

- name: Install the required packages
  ansible.builtin.apt:
    name: "{{required_packages}}"
    update_cache: true

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true
