name: Packer PR Validation or apply
on:
  pull_request:
    branches:
      - main
  pull_request_target:
    types:
      - closed
    branches:
      - main

env:
  AWS_REGION: 'eu-west-2'
jobs:
  packer-validation-or-apply:
    name: Validate packer
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate for the secrets 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:
          role-session-name: GitHubActions
          retry-max-attempts: 5
          aws-region: eu-west-2

      - name: Retrieve secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,dynatrace_tokens

      - name: Authenticate for ami building
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/Dynatrace-Activgate-AMI-Role
          role-session-name: buildActiveGate
          retry-max-attempts: 5
          aws-region: eu-west-2

      - name: Perform a packer build
        run: |
          skip_ami='-var skipAmiCreate=true'
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            skip_ami=''
            echo "Performing a real build."
          else
            echo "This is a PR and therefore performing a dummy build to validate the code."
          fi
          packer build ${skip_ami} packer_config

      - name: Clean up the old AMIs
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "Cleaning up the old AMIs"
            ansible-playbook ansible/cleanup_old_amis.yml
          else
            echo "Skipping cleanup as this is not a real build."
          fi